### ISSUE TITLE
[Suggestion] Add button or field to copy slider values to clipboard

### ISSUE THREAD

**Issue by SirVeggie** [bbc-mc/sdweb-merge-block-weighted-gui#18]
To get the raw values as a string, it is possible to copy them from the console after doing the merge. However sometimes you might not have access to the console at that moment, and it's also easier to copy the values directly from the browser.

Button: click to copy to clipboard\
or\
Field: click, ctrl+A and ctrl+C

Edit: I was getting errors on merge completion (some history file problem) so I didn't realise the slider values are also displayed on the web page upon merge completion. However often I want to copy the values into my clipboard without merging nevertheless.

**Comment by bbc-mc** [comment]
Hi, thank you for request.

I have stress to copy from console :), and I changed merge log displayed on WebUI to show used "base_alpha" and "Weights".
This may help half of your request.

p.s. If you have error include "CheckpointInfo", that is because of changeing hashing system of Auto1111.
Update to use [this commit or later](https://github.com/bbc-mc/sdweb-merge-block-weighted-gui/commit/7988953b2c3f384890d5fd08e2ca2d66f4002e54).
I hope this would help.
